import { promises as fs } from "fs";
import * as path from "path";

async function main() {
  const root = path.join(__dirname, "..");
  const deploymentsDir = path.join(root, "deployments");
  const artifactsDir = path.join(root, "artifacts", "contracts", "SecureLinks.sol");
  const artifactFile = path.join(artifactsDir, "SecureLinks.json");

  // Read ABI from artifact
  const artifactRaw = await fs.readFile(artifactFile, "utf-8");
  const artifact = JSON.parse(artifactRaw);
  const abi = artifact.abi;

  // Network name to chainId mapping (from hardhat.config.ts)
  const networkChainIdMap: Record<string, number> = {
    hardhat: 31337,
    localhost: 31337,
    anvil: 31337,
    sepolia: 11155111,
  };

  // Helper function to get chainId from network name or deployment file
  function getChainId(networkName: string, deployed: any): number | undefined {
    // First try to get from deployment file
    if (typeof deployed.chainId === "number") {
      return deployed.chainId;
    }
    // Fallback to network name mapping
    return networkChainIdMap[networkName.toLowerCase()];
  }

  // Choose target network deployments entry (prefer env -> sepolia -> first)
  let deployedAddress: string | undefined;
  let deployedChainId: number | undefined;
  let chosenNetworkDir: string | undefined;
  try {
    const networks = await fs.readdir(deploymentsDir, { withFileTypes: true });
    const networkNames = networks.filter((e) => e.isDirectory()).map((e) => e.name);

    const envPreferred = process.env.EXPORT_NETWORK || process.env.DEPLOY_NETWORK;
    const preferenceList = [envPreferred, "sepolia", networkNames[0]].filter(Boolean) as string[];

    for (const preferred of preferenceList) {
      if (!preferred) continue;
      if (!networkNames.includes(preferred)) continue;
      const filePath = path.join(deploymentsDir, preferred, "SecureLinks.json");
      try {
        const deployedRaw = await fs.readFile(filePath, "utf-8");
        const deployed = JSON.parse(deployedRaw);
        if (typeof deployed.address === "string" && deployed.address.startsWith("0x")) {
          deployedAddress = deployed.address;
          deployedChainId = getChainId(preferred, deployed);
          chosenNetworkDir = preferred;
          break;
        }
      } catch {}
    }

    // If still not found, scan all as fallback
    if (!deployedAddress || !deployedChainId) {
      for (const entry of networkNames) {
        const filePath = path.join(deploymentsDir, entry, "SecureLinks.json");
        try {
          const deployedRaw = await fs.readFile(filePath, "utf-8");
          const deployed = JSON.parse(deployedRaw);
          if (typeof deployed.address === "string" && deployed.address.startsWith("0x")) {
            deployedAddress = deployed.address;
            deployedChainId = getChainId(entry, deployed);
            chosenNetworkDir = entry;
            break;
          }
        } catch {}
      }
    }
  } catch {}

  // Prepare frontend output dir
  const frontendAbiDir = path.join(__dirname, "..", "..", "frontend", "src", "abi");
  await fs.mkdir(frontendAbiDir, { recursive: true });

  // Write ABI TS file
  const abiTs = `\n/* Auto-generated by backend/scripts/export-frontend.ts */\nexport const SecureLinksABI = ${JSON.stringify({ abi }, null, 2)} as const;\n`;
  await fs.writeFile(path.join(frontendAbiDir, "SecureLinksABI.ts"), abiTs, "utf-8");

  // Write Addresses TS file
  const addresses: Record<string, { address: string; chainId: number; chainName?: string }> = {};
  if (deployedAddress && deployedChainId) {
    const chainName = deployedChainId === 11155111 ? "Sepolia" : undefined;
    addresses[String(deployedChainId)] = {
      address: deployedAddress,
      chainId: deployedChainId,
      chainName,
    };
  }
  const addressesTs = [
    "/* Auto-generated by backend/scripts/export-frontend.ts */",
    "export const SecureLinksAddresses: Record<string, { address: `0x${string}`; chainId: number; chainName?: string }> = "+
      JSON.stringify(addresses, null, 2) +
      " as const;",
    "",
  ].join("\n");
  await fs.writeFile(path.join(frontendAbiDir, "SecureLinksAddresses.ts"), addressesTs, "utf-8");

  console.log("Written:", path.join(frontendAbiDir, "SecureLinksABI.ts"));
  console.log("Written:", path.join(frontendAbiDir, "SecureLinksAddresses.ts"));
  if (chosenNetworkDir) {
    console.log("Source deployments network:", chosenNetworkDir);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});


