/* Auto-generated by backend/scripts/export-frontend.ts */
export const SecureLinksAddresses: Record<string, { address: `0x${string}`; chainId: number; chainName?: string }> = {
  "11155111": {
    "address": "0x286CF2f86832b43d0611064E09401DA6c41bfB2C",
    "chainId": 11155111,
    "chainName": "Sepolia"
  }
} as const;
